# This is a basic workflow to help you get started with Actions
name: Poll CI part

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
        
    - name: Test project Build with Maven
      run: mvn clean install
      
    - name: Print Message
      run : echo "CI Pipeline part Finished successfully!"
